extern crate cc;

use std::path::Path;

fn main() {
    cc::Build::new()
        .flag("-Wno-unused-parameter")
        .include(Path::new("./src/"))
//        .include(Path::new("/usr/include/libnm-gtk"))
//        .include(Path::new("/usr/include/libnm-glib"))
        .include(Path::new("/usr/include/NetworkManager"))
//        .include(Path::new("/usr/include/dbus-1.0"))
        .include(Path::new("/usr/include/gtk-3.0"))
//        .include(Path::new("/usr/include/at-spi2-atk/2.0"))
//        .include(Path::new("/usr/include/at-spi-2.0"))
//        .include(Path::new("/usr/include/dbus-1.0"))
//        .include(Path::new("/usr/lib/x86_64-linux-gnu/dbus-1.0/include"))
//        .include(Path::new("/usr/include/gtk-3.0"))
//        .include(Path::new("/usr/include/gio-unix-2.0/")
        .include(Path::new("/usr/include/cairo"))
        .include(Path::new("/usr/include/pango-1.0"))
//        .include(Path::new("/usr/include/harfbuzz"))
//        .include(Path::new("/usr/include/pango-1.0"))
        .include(Path::new("/usr/include/atk-1.0"))
//        .include(Path::new("/usr/include/cairo"))
//        .include(Path::new("/usr/include/pixman-1"))
//        .include(Path::new("/usr/include/freetype2"))
//        .include(Path::new("/usr/include/libpng16"))
        .include(Path::new("/usr/include/gdk-pixbuf-2.0"))
//        .include(Path::new("/usr/include/libpng16"))
        .include(Path::new("/usr/include/glib-2.0"))
        .include(Path::new("/usr/lib/x86_64-linux-gnu/glib-2.0/include"))
        .file("src/gui/wg-p2p-vpn-editor-plugin.c")
        .file("src/gui/wg-p2p-vpn-editor.c")
       .compile("wg-p2p-vpn-editor");

    cc::Build::new()
        .flag("-Wno-unused-parameter")
        .include(Path::new("./src/"))
//        .include(Path::new("/usr/include/libnm-gtk"))
//        .include(Path::new("/usr/include/libnm-glib"))
        .include(Path::new("/usr/include/NetworkManager"))
//        .include(Path::new("/usr/include/dbus-1.0"))
        .include(Path::new("/usr/include/gtk-3.0"))
//        .include(Path::new("/usr/include/at-spi2-atk/2.0"))
//        .include(Path::new("/usr/include/at-spi-2.0"))
//        .include(Path::new("/usr/include/dbus-1.0"))
//        .include(Path::new("/usr/lib/x86_64-linux-gnu/dbus-1.0/include"))
//        .include(Path::new("/usr/include/gtk-3.0"))
//        .include(Path::new("/usr/include/gio-unix-2.0/")
        .include(Path::new("/usr/include/cairo"))
        .include(Path::new("/usr/include/pango-1.0"))
//        .include(Path::new("/usr/include/harfbuzz"))
//        .include(Path::new("/usr/include/pango-1.0"))
        .include(Path::new("/usr/include/atk-1.0"))
//        .include(Path::new("/usr/include/cairo"))
//        .include(Path::new("/usr/include/pixman-1"))
//        .include(Path::new("/usr/include/freetype2"))
//        .include(Path::new("/usr/include/libpng16"))
        .include(Path::new("/usr/include/gdk-pixbuf-2.0"))
//        .include(Path::new("/usr/include/libpng16"))
        .include(Path::new("/usr/include/glib-2.0"))
        .include(Path::new("/usr/lib/x86_64-linux-gnu/glib-2.0/include"))
        .pic(true)
        .file("src/service/service.c")
       .compile("libservice.a");
}

